#!/usr/bin/env python3
"""Build index-test.html from index.html.

A test build is the same game with two differences, and the second one is the
important one:

  1. It has a cheat panel - instant kill, jump to any floor, god mode, force an
     omen or a nemesis, hand yourself levels and gold.
  2. It cannot touch the real save. Every storage key is prefixed, so the test
     build reads and writes its own profiles and its own Index. Play it for an
     hour, delete it, and the real run is exactly where you left it.

Run it again after any change to index.html:  python3 tools/maketest.py
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / 'index.html'
OUT = ROOT / 'index-test.html'

html = SRC.read_text(encoding='utf-8')

# ---------------------------------------------------------------- 1. the save
# Both storage paths get the prefix: the localStorage fallback and the host
# store. Miss either one and the test build starts eating the real profiles.
subs = [
    ("localStorage.getItem('sd_'+key)", "localStorage.getItem('sdtest_'+key)"),
    ("localStorage.setItem('sd_'+key,", "localStorage.setItem('sdtest_'+key,"),
    ("await window.storage.get(key)", "await window.storage.get('sdtest_'+key)"),
    ("await window.storage.set(key, value)", "await window.storage.set('sdtest_'+key, value)"),
]
for old, new in subs:
    if old not in html:
        sys.exit('maketest: could not find %r - index.html has moved on, '
                 'fix tools/maketest.py before shipping a test build' % old[:48])
    html = html.replace(old, new, 1)

# a title you cannot mistake for the real thing
html, n = re.subn(r'<title>(.*?)</title>', r'<title>⚑ TEST BUILD — \1</title>', html, count=1)
if not n:
    sys.exit('maketest: no <title> to mark')

# ---------------------------------------------------------------- 2. the panel
PANEL_CSS = """
<style id="devcss">
#devbar{position:fixed;left:0;right:0;top:0;z-index:9000;pointer-events:none;
  height:3px;background:repeating-linear-gradient(90deg,#ff5f8a 0 14px,#1a1626 14px 28px);}
#devpanel{position:fixed;right:10px;bottom:10px;z-index:9001;width:214px;
  background:rgba(14,11,24,.97);border:2px solid #ff5f8a;border-radius:4px;
  font:11px ui-monospace,Menlo,Consolas,monospace;color:#e8e2f4;
  box-shadow:0 6px 26px rgba(0,0,0,.6);}
#devpanel h4{margin:0;padding:7px 10px;background:#ff5f8a;color:#1a1626;
  font-size:10px;letter-spacing:.14em;cursor:pointer;display:flex;justify-content:space-between;}
#devbody{padding:9px 10px 11px;display:flex;flex-direction:column;gap:7px;
  max-height:70vh;overflow:auto;}
#devpanel.min #devbody{display:none;}
#devpanel.min{width:auto;opacity:.82;}
#devpanel.min h4{padding:6px 9px;gap:8px;}
#devpanel button{width:100%;padding:6px 8px;background:#241d38;color:#e8e2f4;
  border:1px solid #453a68;border-radius:3px;font:inherit;cursor:pointer;text-align:left;}
#devpanel button:hover{background:#31284d;border-color:#ff5f8a;}
#devpanel button.on{background:#3d1030;border-color:#ff5f8a;color:#ff9ce0;}
#devpanel .dvrow{display:flex;gap:5px;align-items:center;}
#devpanel .dvrow button{width:auto;flex:0 0 auto;}
#devpanel input,#devpanel select{flex:1 1 auto;min-width:0;padding:5px 6px;background:#120f1e;
  color:#e8e2f4;border:1px solid #453a68;border-radius:3px;font:inherit;}
#devpanel .dvnote{color:#8d84a8;font-size:10px;line-height:1.4;}
#devpanel .dvsep{height:1px;background:#332a4d;margin:1px 0;}
#devmsg{color:#8dff9f;font-size:10px;min-height:12px;}
</style>
"""

PANEL_JS = """
<script id="devjs">
/* ------------------------------------------------------------------ TEST BUILD
   None of this exists in the real game. It is generated by tools/maketest.py
   and it writes to its own storage keys, so nothing done here reaches a real
   save. ------------------------------------------------------------------- */
const DEV = {god:false};

/* God mode catches the death itself rather than the hit. The first version of
   this restored health AFTER the monster's turn resolved, which was too late -
   handleDeath had already run inside it, knocked the hero out and pulled the
   next one off the bench, so the health went back onto the wrong character and
   a few swings later the run was over anyway. Wrapping handleDeath instead
   means every source is covered (poison, a boss ultimate, a party wipe) and
   damage still lands and still shows, which is what you want to be looking at
   while you test. You simply do not die. */
const __devDeath = handleDeath;
handleDeath = async function(){
  if(!DEV.god) return __devDeath.apply(this, arguments);
  const st = combatStats();
  App.run.hp = st.maxHp;
  if(partyList().length){
    const h = heroState(partyActiveId());
    h.hp = st.maxHp; h.maxHp = st.maxHp; h.down = false;
  }
  App.run.poison = {turnsLeft:0, perTurn:0};
  App.run.playerBurn = {turnsLeft:0, perTurn:0};
  App.run.playerBleed = {turnsLeft:0, perTurn:0};
  App.run.bossNote = 'God mode — that would have killed you.';
  App.currentPhase = 'postattack';
  const els = getBattleEls();
  if(els.playerHpFill) updateHpBar(els.playerHpFill, els.playerHpNum, App.run.hp, st.maxHp);
  await saveRun();
  render();
};

function devMsg(t){ const m = document.getElementById('devmsg'); if(m) m.textContent = t; }
function devInRun(){ return App.run && App.run.active && App.run.monster; }

async function devKill(){
  if(!devInRun()) return devMsg('not in a fight');
  const m = App.run.monster;
  m.hp = 0;
  const els = getBattleEls();
  if(els.monsterHpFill) updateHpBar(els.monsterHpFill, els.monsterHpNum, 0, m.maxHp);
  devMsg('killed ' + m.name);
  await handleVictory();
}
function devFloor(n){
  n = clamp(parseInt(n,10) || 1, 1, MAX_FLOOR);
  if(!App.run || !App.run.active){
    const party = (App.character.lastParty || []).concat([App.character.classId]);
    startRun(party);
  }
  App.topTab = 'play';
  startFloor(n);
  devMsg('floor ' + n);
}
function devHeal(){
  if(!App.run) return;
  if(partyList().length) partyHealAll(1);
  else App.run.hp = combatStats().maxHp;
  App.run.energy = combatStats().energyMax;
  render(); devMsg('party topped up');
}
function devLevels(n){
  for(let i=0;i<n;i++) grantXp(2000);
  let guard = 0;
  for(;;){
    const prog = classProg();
    const next = (CLASSES[App.character.classId].tree||[]).find(t=>!prog.allocated[t.id] && canAllocate(t, prog));
    if(!next || guard++ > 60) break;
    allocateNode(next.id);
  }
  render(); devMsg('level ' + classProg().level + ', points spent');
}
function devRich(){
  App.character.gems = (App.character.gems||0) + 500;
  if(App.run) App.run.gold = (App.run.gold||0) + 5000;
  MATERIAL_IDS.forEach(m=>addMaterial(m, 50));
  saveCharacter(); render(); devMsg('+5000 gold, +500 gems, +50 of every material');
}
function devGear(){
  const ch = App.character;
  Object.keys(CLASSES).forEach(c=>{
    const w = WEAPON_CATALOG.find(x=>x.classId===c && x.rarity==='legendary');
    if(w){ const it = makeWeaponInstance(w); ch.weapons.push(it); loadoutFor(c, ch).weapon = it.id; }
    ARMOR_SLOTS.forEach(s=>{
      const a = ARMOR_CATALOG.find(x=>x.slot===s && x.rarity==='legendary');
      if(a){ const it = makeArmorInstance(a); ch.armors.push(it); loadoutFor(c, ch)[s] = it.id; }
    });
  });
  saveCharacter(); render(); devMsg('everyone in full legendary');
}
function devOmen(id){
  if(!devInRun()) return devMsg('not in a fight');
  App.run.omen = id || null;
  render();
  if(id) showOmenCard();
  devMsg(id ? ('omen: ' + OMENS[id].name) : 'omen cleared');
}
function devNemesis(){
  if(!devInRun()) return devMsg('not in a fight');
  /* a nemesis never rolls on a boss floor, so ask a floor that is not one */
  let f = Math.max(NEMESIS_MIN_FLOOR, App.run.floor);
  while(isBossFloor(f) && f < MAX_FLOOR) f++;
  if(isBossFloor(f)) f = NEMESIS_MIN_FLOOR + 1;
  let m = null, t = 0;
  while(!m && t++ < 8000){ const g = generateMonster(f, App.character.ngPlus); if(g.nemesis) m = g; }
  if(!m) return devMsg('could not roll one');
  App.run.monster = m;
  render(); devMsg(m.name);
}
function devWipe(){
  if(!confirm('Wipe this TEST build\\'s save? The real game is untouched.')) return;
  try{ Object.keys(localStorage).filter(k=>k.indexOf('sdtest_')===0).forEach(k=>localStorage.removeItem(k)); }catch(e){}
  location.reload();
}

function devPanel(){
  document.body.appendChild(el('<div id="devbar"></div>'));
  const p = el(`<div id="devpanel">
    <h4><span>⚑ TEST BUILD</span><span id="devtog">–</span></h4>
    <div id="devbody">
      <button id="dvkill">☠  Instant kill</button>
      <div class="dvrow"><input id="dvfloor" type="number" min="1" max="${MAX_FLOOR}" value="45"><button id="dvgo">Go</button></div>
      <button id="dvgod">🛡  God mode: off</button>
      <button id="dvheal">✚  Heal party + energy</button>
      <div class="dvsep"></div>
      <div class="dvrow"><select id="dvomen"><option value="">— force an omen —</option></select></div>
      <button id="dvnem">☠  Make it a Nemesis</button>
      <div class="dvsep"></div>
      <button id="dvlv">↑  +10 levels (and spend them)</button>
      <button id="dvgear">⚔  Full legendary, everyone</button>
      <button id="dvrich">🪙  Gold, gems, materials</button>
      <div class="dvsep"></div>
      <button id="dvwipe">🗑  Wipe this test save</button>
      <div id="devmsg"></div>
      <div class="dvnote">Keys: <b>K</b> kill · <b>G</b> god mode. Click the pink bar to collapse — it stays collapsed.<br>Saves to <b>sdtest_</b> keys, so your real game is untouched.</div>
    </div>
  </div>`);
  document.body.appendChild(p);
  const sel = p.querySelector('#dvomen');
  Object.keys(OMENS).forEach(id=>{
    sel.appendChild(el(`<option value="${id}">${OMENS[id].icon} ${OMENS[id].name}</option>`));
  });
  /* It sits over the difficulty buttons when it is open, so once you collapse
     it, it stays collapsed - across reloads too. */
  const setMin = (min)=>{
    p.classList.toggle('min', min);
    p.querySelector('#devtog').textContent = min ? '+' : '–';
    try{ localStorage.setItem('sdtest_devmin', min ? '1' : '0'); }catch(e){}
  };
  let startMin = false;
  try{ startMin = localStorage.getItem('sdtest_devmin') === '1'; }catch(e){}
  setMin(startMin);
  p.querySelector('h4').addEventListener('click', ()=>setMin(!p.classList.contains('min')));
  p.querySelector('#dvkill').addEventListener('click', devKill);
  p.querySelector('#dvgo').addEventListener('click', ()=>devFloor(p.querySelector('#dvfloor').value));
  p.querySelector('#dvfloor').addEventListener('keydown', e=>{ if(e.key==='Enter') devFloor(e.target.value); });
  const gb = p.querySelector('#dvgod');
  gb.addEventListener('click', ()=>{
    DEV.god = !DEV.god;
    gb.textContent = '🛡  God mode: ' + (DEV.god ? 'ON' : 'off');
    gb.classList.toggle('on', DEV.god);
  });
  p.querySelector('#dvheal').addEventListener('click', devHeal);
  sel.addEventListener('change', e=>devOmen(e.target.value));
  p.querySelector('#dvnem').addEventListener('click', devNemesis);
  p.querySelector('#dvlv').addEventListener('click', ()=>devLevels(10));
  p.querySelector('#dvgear').addEventListener('click', devGear);
  p.querySelector('#dvrich').addEventListener('click', devRich);
  p.querySelector('#dvwipe').addEventListener('click', devWipe);
  /* K kills, G toggles god mode - faster than reaching for the panel */
  document.addEventListener('keydown', e=>{
    if(e.target && /INPUT|TEXTAREA|SELECT/.test(e.target.tagName)) return;
    if(e.key === 'k' || e.key === 'K') devKill();
    if(e.key === 'g' || e.key === 'G') gb.click();
  });
}
if(document.readyState === 'loading') document.addEventListener('DOMContentLoaded', devPanel);
else devPanel();
</script>
"""

if '</body>' not in html:
    sys.exit('maketest: no </body> in index.html')
html = html.replace('</body>', PANEL_CSS + PANEL_JS + '</body>', 1)

OUT.write_text(html, encoding='utf-8')
print('wrote %s (%.0f KB)' % (OUT.name, OUT.stat().st_size / 1024))
